//using the get client extension

GET http://localhost:3001/person
###
GET http://localhost:3001/localhost:3001/person/:65018a0144e0198e3f214131


###

POST  http://localhost:3001/person
Content-Type: application/json

{
    "name": "Daya"
}
