//using the get client extension

GET http://localhost:3001/person
###
GET http://localhost:3001/person/Kalio
###

POST  http://localhost:3001/person

Content-Type: application/json

{
    "name": "Mark"
}
